### ISSUE TITLE
Potential exploit: attack and scrap Mech on same turn

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#169]
Right now it is possible to attack with a Mech, and then Scrap the same Mech on the same turn. I think this may lead to possible exploits, especially with cards that have Rush. Do you think this should be remedied?

**Comment by Zomis** [comment]
Probably yes, the question is just *how*. Should we always require a Mech to be able to attack in order for it to be possible to scrap? Right now it is also possible to play a Mech and scrap it on the same turn (for non-rush Mechs), should that be allowed?

There are two different variables involved here, one is SICKNESS and one is ATTACK_AVAILABLE.
For cards with Rush, SICKNESS is always 0.
For all cards that can attack, ATTACK_AVAILABLE is 1 before they attack on a turn.

I think a possible good solution would be to simply require both SICKNESS to be 0 and ATTACK_AVAILABLE to be 1 in order to scrap a Mech. In that case, the following scenarios exist:

- Play a non-rush Mech and scrap it directly - **denied**
- Play a non-rush Mech and scrap it on your next turn - **allowed**
- Play a non-rush Mech and attack on your next turn and then scrap - **denied**
- Play a Mech with rush and scrap it directly - **allowed**
- Play a Mech with rush and attack, and then scrap - **denied**

**Comment by Phrancis** [comment]
I think that would work, though it would make one particular card not very handy. The 0/1 Mech cost 0 mana giving 3 scraps I find myself frequently just casting and scrapping on the same turn to get Scrap for an Upgrade I need that turn. Could we maybe tweak it to where a creature that *cannot* attack be available to scrap on the same turn it is cast?

**Comment by Zomis** [comment]
Of course, they could be given Rush to fix that :)

**Comment by Phrancis** [comment]
Whatever you think is best, if that works then yes we would just need to slightly edit the game rules to say *"a Mech creature can attack or scrap on the same turn it is cast."* :)

**Comment by Zomis** [comment]
Not all Mech creatures, only the Mechs with Rush or the Mechs without attack!

**Comment by Phrancis** [comment]
Well, yeah I assumed that's what we were talking about LOL. I say we go ahead and push that for next snapshot then. Would it just be a matter of updating which Mechs with 0 (or more) attack have the Rush attribute? If so I can make an updated Excel document (or whatever works for you).

**Comment by Zomis** [comment]
I will also need to make a slight change to the systems involved in `Scrap`. I don't think there is a need for a new Excel document this time, if any questions about it occur I will ask you. (I should really work on #164, #138 and related issues to make it easier for you to add/modify cards...)
