### ISSUE TITLE
JS game logic - How best to document for modding?

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#203]
With the recent advent of JS-based game logic (thanks @Zomis !) I began thinking about how best to document now, and later, for eventual modders to effectively use. I had a few initial thoughts of options:

- Write a modder's guide on the website;
- Write a modder's guide in the repo (like a `.md` file);
- Write a modder's guide on the Github wiki;
- Write a modder's guide mostly as code documentation (e.g., JSDoc);
- Combination thereof.

I'll be happy to write the documentation as we go along, one way or the other, but I just need to make sure we agree on the best method. I like that the first 3 allow for formatting, and especially on the website where we can use BootStrap elements to our advantage. It's a bit more work, and a few other strings attached, but I think it would be best UX. 

On the other hand, while I think we absolutely should at least use JSDoc in the code,  having the modding guide there would have the advantage of keeping everything in one place, so the whole project is self-documenting. Albeit, that may hinder the readability of the code to an extent by adding a lot of "noise" in the source files, and perhaps not be very intuitive to the potential modder.

**Comment by ckuhn203** [comment]
Definitely use JSDoc and be very thorough when documenting the API, but it's not exactly the place for a "Guide". I would recommend running the JSDoc through a tool to get it in HTML format to produce something like I did for our [Source Control API][scDoc]. I did it by hand, because I needed markdown, but I'm sure there are tools out there.

The guide itself could be in the form of a detailed tutorial or as simple as an [example usage][ex]. 

[scDoc]:https://github.com/retailcoder/Rubberduck/wiki/Source-Control-API
[ex]:https://github.com/retailcoder/Rubberduck/wiki/Source-Control-API#example-usage

**Comment by Phrancis** [comment]
@ckuhn203 great advice, thanks for chiming in!

**Comment by Phrancis** [comment]
I have documented how the cards are customized, for the most part. What other aspects of the game logic can be changed via the JavaScript implementation, @Zomis ?

**Comment by Phrancis** [comment]
I think the latest commits provide "good enough" documentation for the time being, although new documentations should be written as new things are implemented.
