### ISSUE TITLE
New mod: "Mythos"

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#223]
@MGS1GreyFox and I were discussing what other mod we could do besides Cyborg Chronicles. I'm opening this for others to discuss and suggest ideas. Here are some early thoughts we had:

- The theme will feature characters from various mythologies as the cards; this will make it easy to come up with names, descriptions and images.
- Stats and effects of cards will be inspired from mythological characters' stories
- The game will (eventually) bring a new game concept of hero cards (will open an issue with more details)
- The Scrap+Upgrade mechanic will not be central to the game
- Most if not all cards will have special effects; this will help us showcase the flexibility of the card modding features

Bring in your exciting ideas now!

**Comment by Zomis** [comment]
Great start!

Here are some further questions about this mod:

- Will the scrap + upgrade mechanic exist at all?
- How should Mana work?
- How should attacking work? (with blocking?)
- Should there be two rows on the battlefield on this one? (this idea has come up before)
- What other properties should exist on cards? Ranged? Taunt? Rush? Some new ones?

**Comment by Phrancis** [comment]
I think Scrap could be used creatively but differently, triggering effects instead of resources. Imagine for example:
**"Hades"**: "Can return to the Underworld and take one enemy with him"
_(on Scrap, reduce one opponent's card to 0 health)_

**Comment by Zomis** [comment]
Okay, so essentially it's not scrap at all :) Just some effects that can be triggered (that also seem to destroy the creature).

I suspect that you will want the discard pile concept, as specified in #212, to be implemented for this mod?

**Comment by Phrancis** [comment]
This mod would be a great candidate for the discard pile, yes. Depending of whether we are shooting for 0.6 or 0.7 on this one (I'd prefer 0.6) we may or may not need the discard pile feature at first and just implement it in the mod later when it's available.

**Comment by Phrancis** [comment]
Just found an awesome website we can use for reference to the various mythologies: **[GodChecker.com](http://www.godchecker.com/)**

**Comment by Zomis** [comment]
I agree that aiming for 0.6 for this one is good, and also implementing more features in the mod as they're supported.

**Comment by Phrancis** [comment]
I just thought of an interesting set of game mechanics, please comment
- Max Mana is fixed, as in, it does not increase at each turn, you start with full mana right out of the gate
- Mana is used throughout the life of the card, meaning that the used Mana would not restore after each turn (I think this could be done as a card effect)
- I think for this I would like to use HS-style attacking/blocking, with the inclusion of taunt and rush mechanics
@Zomis do you see any problem with any of these in the current implementation?

**Comment by Zomis** [comment]
I'm not entirely sure what you mean by "Mana is used throughout the life of the card"... Let's say for example that I have 100 max mana, and I play a card that costs 5 mana. Does this mean that as long as that card is in play, I have 95 mana? Will I have 100 mana again when that card leaves play? If not, can I then get mana some other ways? (Maybe some special "mana producer" cards that produce mana either each turn or when played so that I have the possibility to reach my max mana again?)

I like the ideas, and see not any problem at all when it comes to the implementation. It should be supported easily.

**Comment by MGS1GreyFox** [comment]
@Phrancis Oh man, I LOVE the thought of having a fixed mana pool just to see how it would play. Are you saying that you would have a max team cost for what could be out on the field at any one time? 

For example, max mana 10 = max cost of all creatures in play can not exceed 10 mana cost? Because I really like that concept. Not only because of the strategic standpoint (I'm all about some strategy) but it would be a neat check and balance for people that have a lot of spells but they have to manage their creatures mana cost efficiently, so they still have a mana pool to cast spells. 

I agree as well that if we go that route then the HS style would benefit gameplay the most. You have to strategically place units out, and you get to decide what attacks what and health does not come back. That way you aren't forced to wait for your opponent to decide blockers and potentially wreck your set up. VERY good thoughts. 

Finally, fantasy setting is my bread and butter, so I'm very excited about the premise of this mod, this is something that could really be a fresh idea for a TCG. (eventually I'll do a big write up on a 2 row battlefield, but for this mod I don't think that will be necessary.)

**Comment by Phrancis** [comment]
@Zomis  @MGS1GreyFox to clarify, yes if I had 100 Mana, and played a 5 Mana card, I would be "stuck" at 95 Mana until that card is removed from play.

**Comment by skiwi2** [comment]
What about the card using more mana every turn, but once it goes out of play you get it all back?

Like at start 20 mana, then every turn plus 5.

Also another idea to add could be that cards that get destroyed rather than go to the graveyard do not return their mana?

**Comment by MGS1GreyFox** [comment]
@skiwi2 My only concern with cards not giving back mana if they are destroyed/exiled is if you build a deck around that mechanic it could be exploited to the point where a player couldn't play at all. You wouldn't one to get in a position where you are stonewalled to only use 1 mana cost items. Adding speel cards that up your mana could circumvent that, but I'm not sure how well it would play. 

As far as cards gradually costing more mana, I think that could be useful for cards that are VERY powerful, as their cost increases there has to be something for the player as well to gain, you wouldn't want a card just sapping your mana for no reason, there should be a purpose behind it. But I think this idea could be good for certain situations.

**Comment by Phrancis** [comment]
If we did that increasing Mana cost, we would need to have some form of mechanic where you could voluntarily kill your card though, lest you hamstring yourself into having very little Mana left for other cards.

**Comment by MGS1GreyFox** [comment]
@Phrancis I think a card with an increasing mana cost could just have a mechanic "deal X damage when destroyed/removed from play" where X is the amount the mana cost raised since the initial cost. That was once it does go, it's likely to take something out with it. Just a little check and balance. Of course the effects would have to be dependent on the card, but I think that could be a good way to start.

As far as voluntarily killing your card, I think we should just put a spell in with an effect like that. That way you have a synergy in your deck, but you have to have the draws to make it happen. I don't think a mechanic to kill your cards as you wish would work well, and kind of undermines the idea of a fixed mana system.

**Comment by Phrancis** [comment]
Ah yes I like the idea of having a spell for that, should be easy to do too in JS

**Comment by Zomis** [comment]
What about the Hades idea from yesterday?

> "Hades": "Can return to the Underworld and take one enemy with him"
> (on Scrap, reduce one opponent's card to 0 health)

That sounds like a way to voluntarily get rid of your cards to me. But whatever effects you choose, I approve! I do like the synergy ideas!

**Comment by MGS1GreyFox** [comment]
@Zomis I'm think that may be more of a hero effect ala HS. If Hades is your "God" then he has that ability and may work on a cooldown. We're spit balling right now anyway but I think that would be a cool thing, but I don't think it's a mechanic that should be available every turn if so. We'll iron out the specifics soon!!

**Comment by Phrancis** [comment]
I think for this mod, damage should persist from turn to turn, Hearthstone style.

**Comment by Phrancis** [comment]
After giving this some though, I think a value of 100 for Mana might work good. It will have more precision than say, 10, and also carry the familiar "Percent" used. Any objections?

**Comment by Zomis** [comment]
It might be good to have the max mana increase by 10 every turn, until it reaches a maximum of 100, so that you cannot use all your best cards turn 1.

Some questions also:

- How should mulligan work? Choose single cards, mulligan all or nothing (with a possible hand size penalty for each mulligan), should it be available at all?
- How many starting cards on a player hand?

**Comment by Phrancis** [comment]
I think for mulligan we can use the same rules as the other mod, though I'm not opposed trying something different too.

Let's try that "increase by 10" idea for a spin, you're probably right that starting at full mana is a bit much

**Comment by Phrancis** [comment]
I think we're safe to say this one is done, as of 0.6 official. More cardsets will be added as time goes but this one is pretty much cemented.
