### ISSUE TITLE
Clarify or improve "enchantment()"

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/Cardshifter#287]
At the current time, this is a bit ambiguous. The effects work, but don't display. They also don't follow the same syntax as we have been using for other effects. See attached screenshot from [documentation](https://github.com/Cardshifter/Cardshifter/blob/mods/Documentation/1&#40;%20Card%20Library%20-%20Basics.md#enchantments): 

![enchantments](https://cloud.githubusercontent.com/assets/8539648/8022527/7862c864-0ca5-11e5-94e7-dcf5d4fc7ef3.png)

**Comment by Zomis** [comment]
Suggestions for how it should be done? Should it be specified in the 'effects' field instead of being shown as pure attack and health?

**Comment by Phrancis** [comment]
I think to have a syntax similar to spells might actually work better. From my point of view, the only big differences is that enchantments are always cast as add-ons to your own creatures on Battlefield (and sometimes of a certain type, e.g., Bios for Cyborg-Chronicles), and of course the cost in SCRAP, which again only applies for Cyborg. (we could very well give them a MANA cost as well in different mods/settings). Does that make sense? If not LMK I'll try to come up with some examples

**Comment by Zomis** [comment]
So you primarily want to change the DSL for how to write the enchantments? And have them show differently in game? So that they are more equal to spells, in both those aspects?

**Comment by Phrancis** [comment]
I would say that's a good way to summarize it. Just to compare... this current syntax:

    card('Adrenalin Injection') {
        flavor "An injection to increase speed and body function."
        enchantment true
        set(SICKNESS, 0) // give "Rush"
        addAttack 1
        addHealth 1
        scrapCost 1
    }

Perhaps instead could be like:

    card('Adrenalin Injection') {
        flavor "An injection to increase speed and body function."
        scrapCost 1
        enchantment {
            targets 1 cards { /** targets are already specified in Game rules config */ }
        }
        afterPlay {
            set SICKNESS to 0 on targets // give "Rush"
            change ATTACK, HEALTH by 1 on targets
        }
    }

**Comment by Zomis** [comment]
How about this?

    card('Adrenalin Injection') {
        flavor "An injection to increase speed and body function."
        enchantment true // can also be `enchantment()`
        afterPlay {
            set SICKNESS to 0 on targets // give "Rush"
            change ATTACK, HEALTH by 1 on targets
        }
        scrapCost 1
    }

**Comment by Phrancis** [comment]
That would work really good too, with the assumption that Enchantments are only ever going to have 1 target (which is how it is supposed to work right now anyways)

**Comment by jacwah** [comment]
This issue is a bit complex so I'll try to summarize it. The issue has two parts that should be handled separately. Documentation should always be a part of adding or changing features, but is not the core of this issue.

#### 1. Change the syntax of enchantments

The new syntax is discussed above. The last suggestion by @Zomis seems to have been agreed upon. The `afterPlay` effect will be the primary way for an enchantment to affect its target.

```
card('Adrenalin Injection') {
    flavor "An injection to increase speed and body function."
    enchantment true // can also be `enchantment()`
    afterPlay {
        set SICKNESS to 0 on targets // give "Rush"
        change ATTACK, HEALTH by 1 on targets
    }
    scrapCost 1
}
```

#### 2. Make enchantments "attach" to other cards

Right now, enchantments simply change the resource values of an entity without any way to track them. Changing this is also discussed in #362. Making enchantments its own component would lead to several benefits:

- Enable enchantments to be shown in UI.
- Dynamic enchantments.

> This can be accomplished by creating a new component that contains a Set/List/Collection of entities.

-- @Zomis in #362.

**Comment by Zomis** [comment]
I think issue 362 should cover making enchantments attach to other cards, that is not a part of this issue.

And now, looking back at this issue again, it strikes me that the proposed syntax would work in the same way as this: (which should already be supported, not 100% sure that the syntax below is correct but the support for it should be there somewhere already)

    card('Adrenalin Injection') {
        flavor "An injection to increase speed and body function."
        spell {
             targets 1 cards {
                 creature()
                 zone 'Battlefield'
             }
        }
        afterPlay {
            set SICKNESS to 0 on targets // give "Rush"
            change ATTACK, HEALTH by 1 on targets
        }
        scrapCost 1
    }

So `enchantment` could perhaps be simply the same thing as writing

    spell {
         targets 1 cards {
             creature()
             zone 'Battlefield'
         }
    }

and then the whole thing can be fixed by editing the cardsets.

**Comment by jacwah** [comment]
I have implemented almost all of the new enchantment syntax on the [issue287](https://github.com/Cardshifter/Cardshifter/tree/issue287) branch.

What still remains is a way to apply mod wide enchantment filters in `Game.groovy`. In Cyborg-Chronicles, enchantments can only target Bio creatures. This was previously done in a `targets` clause under `action ('Enchantment')`, but that doesn't work here since that clause is already used in `enchantment.groovy`.

I have already set up a failing test for this in TestMod.
