### ISSUE TITLE
Negate onCards { ... } filters

### ISSUE THREAD

**Issue by newbiedoodle** [Cardshifter/Cardshifter#288]
Kinda surprised that no one has suggested this yet.

Sometimes, you want to do damage to every creature _not_ of a certain type, or _not_ whatever. Therefore, we should probably have negation in `onCards { ... }` (and anywhere else that filters that I haven't seen yet).

[(Thanks to @Phrancis  for the syntax idea)](http://chat.stackexchange.com/transcript/message/22053333#22053333)

```
change HEALTH by -1 onCards {
    creatureType not "Greek Hero"
    ownedBy "opponent"
}
```

**Comment by Zomis** [comment]
Syntax for this will likely be more like this:

    change HEALTH by -1 onCards {
        not { creatureType "Greek Hero" }
        ownedBy "opponent"
    }

**Comment by jacwah** [comment]
Should a `not` block negate all filters within it as a whole

    !(filter1 && filter2 && filterN)

or should it negate each filter individually?

    !filter1 && !filter2 && !filterN

**Comment by Zomis** [comment]
Looking at some possible cases:

`!(a && b && c)` is true if for example a = true, b = true, c = false (it is the same as `!a || !b || !c`)

`!a && !b && !c` is true if and only if a = false, b = false, c = false

And then let's look at a possible use-case: **Example 1:**

    change HEALTH by -1 onCards {
        not {
            creatureType "Greek"
            ownedBy "opponent"
        }
    }

and then also consider what this would mean: **Example 2:**

    change HEALTH by -1 onCards {
        not {
            ownedBy "opponent"
        }
        not {
            creatureType "Greek"
        }
    }

(The DSL is not optimal for how to declare this negation, but let's ignore that for now)

Let's say that there are four cards in play:

A: Greek owned by you
B: Roman owned by you
C: Greek owned by opponent
D: Roman owned by opponent

From Example 2, I think it is clear that the only allowed target should be B, not owned by opponent and not Greek.

In Example 1, I think the expected behavior would be to only exclude card C, which is a Greek card owned by opponent. Which means that in Example 1, cards A, B and D would be allowed targets.

So it seems to me like negate all filters as a whole, i.e. `!(a && b && c)`
