### ISSUE TITLE
User name validation

### ISSUE THREAD

**Issue by jacwah** [Cardshifter/Cardshifter#354]
_What user names are valid?_

This question recently sprung up with #345. It started with duplicated names, then @Phrancis mentioned empty ones. The code that closes that question adds the method  `Server.isValidUserName` which makes user name validation easy to implement.

In the issue above, I ended up posting a suggested set of rules for user names.

>A user name...
>- is unique. Two clients can not connect with the same name simultaneously.
>- is at least 1 character and at most 20 characters long.
>- contains only ASCII letters, spaces, underscores and decimal numbers.
>- does not begin or end with whitespace.

- A too long user name doesn't make sense and is annoying for UI development and to type.
- Carefully crafted bytes can e.g. mess up a terminal window where logging is done and cause all sorts of trouble. It may also not be typeable.
- Is that `x` spaces or a tab?
- Names starting or ending with whitespace are confusing.

**Comment by Phrancis** [comment]
_"contains only ASCII letters, spaces, underscores and decimal numbers"_ I'm assuming would also exclude problematic characters like slashes, quote marks and the like, correct?

At some point in the future we _may_ want to consider a more expansive allowed character set (perhaps with explicit exclusions instead of explicit inclusions) but for the foreseeable future I think what you suggested above should be completely reasonable.

**Comment by jacwah** [comment]
Yes, with letters I mean alphabetic lettters `[a-zA-Z]`.

**Comment by jacwah** [comment]
The name "Server" should be reserved as well, since there's no other way to tell user messages from server messages in the chat.

**Comment by Phrancis** [comment]
The name "undefined" also should be reserved, as it is used for client-bound chat message broadcasting to client. @SirPython can confirm that.

**Comment by Zomis** [comment]
Don't allow more than one consecutive space, such as `some  name` --> `some name`
