### ISSUE TITLE
A GetZoneMessage?

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/Cardshifter#357]
Perhaps the client would benefit from having a `GetZoneMessage`, which would be a message that returns the entities of a zone based on the name, the ID, and the owner(maybe no ID or no name) The server would then return all the information about the specified zone.

The client could benefit from this, for example in the beginning of a game: rather than the client having to pick through and try to decipher `ZoneChangeMessage`s so that the client knows what cards are where, the client simply needs to send a `GetZoneMessage` and read all the entities in the return message.

**Comment by Zomis** [comment]
I think `ZoneChangeMessage` helps reduce the network traffic used by the game. I don't really see a reason for `GetZoneMessage`. From what I'm hearing, it would be only be used early on in the game because.... well... because why exactly? What is the problem about deciphering ZoneChangeMessages? You need to do that at some point anyway. Or do you intend on sending `GetZoneMessage` requests after each turn and determine what cards have moved where?

**Comment by SirPython** [comment]
@Zomis "Or do you intend on sending GetZoneMessage requests after each turn and determine what cards have moved where?" Yes, that was the intention: simply update all the zones after every... never mind. Thinking about it again, it seems too overkill.

**Comment by Zomis** [comment]
My point exactly.
