### ISSUE TITLE
Alias MANA_MAX and MAX_MANA in clients

### ISSUE THREAD

**Issue by jacwah** [Cardshifter/Cardshifter#412]
This has to be done before #398 can be merged. The change should be made in all clients. The ability to alias resources in clients will make renaming resources easier in the future.

**Comment by jacwah** [comment]
I've now examined the JavaFX client. It needs no changing as it just displays all resources sent from the server. See `GameClientController::processUpdateMessage` and `GameClientController::processUpdateMessageForPlayer`.

![Screenshot](https://cloud.githubusercontent.com/assets/3816754/10172144/21477b86-66de-11e5-83e9-62346c6afdc0.png)

**Comment by jacwah** [comment]
Web client now tested too. It works the same way as JavaFX and just displays whatever is sent to it.

![Screenshot](https://cloud.githubusercontent.com/assets/3816754/10173664/bcf8e3c4-66e5-11e5-925a-6df794e86578.png)

**Comment by Zomis** [comment]
Note that the reason for why no change is needed is because those clients at the moment simply lists *all* available resources on players. At a later time, at least in the Web-Client, I expect things to work differently. By only showing some "expected" resources, it will likely look better.

If this resource would have been on cards, a lot more changes would be required.

**Comment by jacwah** [comment]
The LibGDX client does not use the max mana resource at all. See the `PlayerView` constructor.

![Screenshot](https://cloud.githubusercontent.com/assets/3816754/10174251/1ac9579c-66e9-11e5-9b71-dec857a7a7c4.png)
